tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "openssl@1.1"
brew "curl"
brew "git"
brew "gmp"
brew "libyaml"
brew "mysql", restart_service: true
brew "readline"
brew "ruby-build"
brew "rbenv"
brew "yarn"
